name: STL file generation
on: [push]
jobs:
  generate-stl-files:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repo'
        uses: actions/checkout@v4.2.2
      - name: 'Reusable strings'
        id: strings
        shell: bash
        run: echo "build_dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: 'Install OpenSCAD'
        run: sudo apt install -y openscad
      - name: 'Configure CMake'
        run: cmake -B ${{ steps.strings.outputs.build_dir }}
      - name: 'Generate STL files'
        run: cmake --build ${{ steps.strings.outputs.build_dir }}
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.strings.outputs.build_dir }}/*.stl
